; Allow file uploads for up to 100MB

upload_max_filesize = 100M

; Allow processing up to 100MB

post_max_size = 100M

; Add support for XDebug connections

xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.log_level = 0

; Hide the deprecation messages by default  

error_reporting = E_ALL & ~E_DEPRECATED

log_errors = On
error_log = /var/log/php_errors.log
display_errors = On
display_startup_errors = On

; Enable PHP-FPM slow log
slowlog = /var/log/php-fpm-slow.log
request_slowlog_timeout = 5s

; PHP-FPM access log
access.log = /var/log/php-fpm-access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"

; Increase log detail
log_level = debug

; Make sure logs are flushed immediately
log_errors_max_len = 0
ignore_repeated_errors = Off